WebAdmin/WebAdmin/Models/Message.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebAdmin
{


    public class Message
    {
        [HiddenInput(DisplayValue = false)]
        [Display(Name = "Id")]
        [Key]
        [DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]
        //    public Guid MessageId { get; set; }
        public Guid MessageId { get; set; } = Guid.NewGuid();
        [Display(Name = "Title")]
        [Required(ErrorMessage = "Required *")]
        public string MessageTitle { get; set; }
        [Display(Name = "Subject")]
        [Required(ErrorMessage = "Required *")]
        public string Subject { get; set; }


        //[HiddenInput(DisplayValue = false)]
        //[DataType(DataType.DateTime)]
        //public DateTime StartDate { get; set; }



        //[HiddenInput(DisplayValue = false)]
        //[DataType(DataType.DateTime)]
        //public DateTime EndDate { get; set; }
        //  [HiddenInput(DisplayValue = false)]
        // [DataType(DataType.DateTime)]
        //public string TimeZone { get; set; }

        [AllowHtml]
        [Required(ErrorMessage = "Required *")]
      //  [HiddenInput(DisplayValue = false)]
        public string Description { get; set; }
        [HiddenInput(DisplayValue = false)]
        [Display(Name = "Language")]
        public Guid LanguageId { get; set; }



    }
}

WebAdmin/WebAdmin/Models/ViewModels/MessageViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAdmin.Models;

namespace WebAdmin

{
    public class MessageViewModel
    {
        public GridViewModel<Message> messageGridViewmodel => new GridViewModel<Message>();
        public Message MessageDetails { get; set; }

        //public Guid Id { get; set; }
        //public Guid LanguageId { get; set; }
        //public string LanguageString { get; set; }
        //public string Title { get; set; }
        //public string Description { get; set; }
        //public DateTime StartDate { get; set; }
        //public DateTime EndDate { get; set; }
    }
}

WebAdmin/WebAdmin/Controllers/MessageController.cs
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;

namespace WebAdmin
{
    public class MessageController : WebAdminController
    {
        private readonly IDataRepository<Message> messageRepository;
        private readonly IDataRepository<Language> languageRepository;
        private readonly IDataRepository<EventMessage> eventMessageRepository;
        private readonly ICultureCodeService cultureCodeService;


        /// <summary>
        /// Initializes a new instance of the <see cref="MessageController"/> class.
        /// </summary>
        /// <param name="messageRepository">
        /// The message repository.
        /// </param>
        /// <param name="eventMessageRepository">
        /// The event message repository.
        /// </param>
        /// <param name="languageRepository">
        /// The language repository.
        /// </param>
        ///  /// <param name="cultureCodeService">
        /// The cultureCodeService.
        /// </param>
        public MessageController(IDataRepository<Message> messageRepository,
                                 IDataRepository<EventMessage> eventMessageRepository,
                                 IDataRepository<Language> languageRepository,
                                 ICultureCodeService cultureCodeService)
        {
            this.messageRepository = messageRepository;
            this.eventMessageRepository = eventMessageRepository;
            this.languageRepository = languageRepository;
            this.cultureCodeService = cultureCodeService;


        }
        /// <summary>
        /// To View Message Details and Populate Language ComboBox
        /// </summary>
        /// <returns>ActionResult</returns>
        public async Task<ActionResult> MessageIndex()
        {
            var messageViewModel = new MessageViewModel();

            try
            {
                var languageSelectList = new List<SelectListItem>();
                IEnumerable<Language> language = await languageRepository.GetDatas();
                IEnumerable<Language> enumerable = language.ToList();

                if (enumerable.Any())
                {
                    foreach (Language data in enumerable)
                    {
                        if (Convert.ToString(data.Enabled) == "True")
                        {
                            languageSelectList.Add(
                                new SelectListItem
                                {
                                    Value = data.Id.ToString(),
                                    Text = CreateLanguageWithCultureCode(data)
                                });
                        }
                    }
                    ViewBag.languages = languageSelectList.OrderBy(x => x.Text);

                }
            }
            catch (Exception exception)
            {
                MvcApplication.Logger.Error(exception.Message, exception);

            }

            return View(messageViewModel);
        }



        /// <summary>
        /// To View Event Message Details and populate Message and TimeZone ComboBox
        /// </summary>
        /// <returns>ActionResult</returns>
        public async Task<ActionResult> EventMessageIndex()
        {
            var eventMsgViewModel = new EventMessageViewModel();
            var messageSelectList = new List<SelectListItem>();
            ViewData["MessageId"] = messageSelectList;
            try
            {


                IEnumerable<Message> messages = await messageRepository.GetDatas();
                IEnumerable<Language> languages = await languageRepository.GetDatas();

                string[] requestUserLanguages = Request.UserLanguages;

                if (requestUserLanguages != null)
                {
                    string userLanguage = Convert.ToString(Convert.ToString(requestUserLanguages.First().Split('-').First()));

                    IEnumerable<Language> languageLst = languages.ToList();

                    IEnumerable<Message> messageLst = messages.ToList();

                    if (languageLst.Any() && messageLst.Any())
                    {
                        ViewData["MessageId"] = MessageHelper.GetMessagesList(languageLst, messageLst, userLanguage).OrderBy(x => x.Text);
                        var timezoneSelectList = new List<SelectListItem>();
                        var timeZone = TimeZoneInfo.GetSystemTimeZones();
                        foreach (TimeZoneInfo data in timeZone)
                        {
                            timezoneSelectList.Add(
                                new SelectListItem
                                {
                                    Value = data.DisplayName,
                                    Text = data.DisplayName
                                });

                        }
                        // timezoneSelectList.OrderBy(x => x.Text);
                        ViewBag.timezone = timezoneSelectList.OrderBy(x => x.Text);
                    }
                }
            }
            catch (Exception exception)
            {
                MvcApplication.Logger.Error(exception.Message, exception);

            }


            return View(eventMsgViewModel);
        }




        /// <summary>
        /// To populate grid with Message details
        /// </summary>
        /// <param name="request">request</param>
        /// <returns>ActionResult</returns>
        [HttpPost]
        public async Task<ActionResult> MessageRead([DataSourceRequest] DataSourceRequest request)
        {
            try
            {

                IEnumerable<Message> messagesLst = await this.GetDataBaseFunction<Message>(request, this.messageRepository);

                IEnumerable<Message> enumerable = messagesLst.ToList();

                foreach (Message message in enumerable)
                {

                    message.Description = Regex.Replace(message.Description, "<startdate>", "&lt;Startdate&gt;", RegexOptions.IgnoreCase);
                    message.Description = Regex.Replace(message.Description, "<starttime>", "&lt;Starttime&gt;", RegexOptions.IgnoreCase);
                    message.Description = Regex.Replace(message.Description, "<enddate>", "&lt;Enddate&gt;", RegexOptions.IgnoreCase);
                    message.Description = Regex.Replace(message.Description, "<endtime>", "&lt;Endtime&gt;", RegexOptions.IgnoreCase);

                    message.Description = message.Description.Replace("?", " ");
                }
                DataSourceResult result = enumerable.ToDataSourceResult(request);
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            catch (Exception exception)
            {
                MvcApplication.Logger.Error(exception.Message, exception);
                throw;
            }
        }



        /// <summary>
        /// To get Message description of a message in a grid edit popup window
        /// </summary>
        /// <param name="messageId">messageId</param>
        /// <returns>ActionResult</returns>
        [HttpPost]
        public ActionResult GetMessageDescriptionById(string messageId)
        {
            string description = string.Empty;
            IEnumerable<Message> getAll = AsyncUtilHelper.AsyncUtil.RunSync(() => messageRepository.GetDatas());
            Message getById = getAll.Where(x => x.MessageId == Guid.Parse(messageId)).FirstOrDefault();
            if (getById != null)
            {
                description = getById.Description;
            }
            description = Regex.Replace(description, "<startdate>", "&lt;Startdate&gt;", RegexOptions.IgnoreCase);
            description = Regex.Replace(description, "<Enddate>", "&lt;Enddate&gt;", RegexOptions.IgnoreCase);
            description = Regex.Replace(description, "<Starttime>", "&lt;Starttime&gt;", RegexOptions.IgnoreCase);
            description = Regex.Replace(description, "<Endtime>", "&lt;Endtime&gt;", RegexOptions.IgnoreCase);


            description = description.Replace("?", " ");
            return Json(description);
        }

        /// <summary>
        ///  To populate grid with event message details
        /// </summary>
        /// <param name="request">request</param>
        /// <returns>ActionResult</returns>

        [HttpPost]
        public async Task<ActionResult> EventMessageRead([DataSourceRequest] DataSourceRequest request)
        {
            try
            {
                var eventMessageCollection = new List<EventMessage>();
                IEnumerable<EventMessage> getAllEventMessages = await this.GetDataBaseFunction<EventMessage>(request, eventMessageRepository);

                IEnumerable<Message> getAllMessages = AsyncUtilHelper.AsyncUtil.RunSync(() => messageRepository.GetDatas());
                IEnumerable<Language> getAllLanguage = AsyncUtilHelper.AsyncUtil.RunSync(() => languageRepository.GetDatas());
                // ReSharper disable once StyleCop.SA1305
                var isAdded = false;
                if (Request.Cookies["TimeZoneClient"] != null)
                {
                    string timezone = Convert.ToString(this.Request.Cookies["TimeZoneClient"].Value);
                    string[] requestUserLanguages = this.Request.UserLanguages;
                    if (requestUserLanguages != null)
                    {
                        var defaultCode = "";
                        string defaultLanguage = Convert.ToString(WebConfigurationManager.AppSettings["DefaultLanguage"]);
                        foreach (LanguageName language in Enum.GetValues(typeof(LanguageName)))
                        {

WebAdmin/WebAdmin/Views/Shared/_Footer.cshtml
<footer>
    <p class="b-color"><span>&copy;</span> 2019.All Rights Reserved. <a href="">Privacy Policy</a> <span> &vert; </span> <a href="">Terms and Conditions</a></p>
</footer>

WebAdmin/WebAdmin/Views/Shared/_Header.cshtml
<!-- top navigation -->
<div class="top_nav">
    <div class="nav_menu">
        <nav class="bg-light">
            <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>
            <div class="nav toggle">
                <img src="@Url.Content("~/Content/Images/DPS_Maxframe_logo.jpg")">
            </div>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <img src="@Url.Content("~/Content/Images/userAvathar.jpg")" alt="">John Doe
                    </a>
                </li>

                <li role="presentation" class="dropdown">

                    <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
                        <li>
                            <a>
                                <span class="image"><img src="@Url.Content("~/Content/Images/userAvathar.jpg")" alt="Profile Image" /></span>
                                <span>
                                    <span>John Smith</span>
                                    <span class="time">3 mins ago</span>
                                </span>
                                <span class="message">
                                    Film festivals used to be do-or-die moments for movie makers. They were where...
                                </span>
                            </a>
                        </li>
                        <li>
                            <a>
                                <span class="image"><img src="@Url.Content("~/Content/Images/userAvathar.jpg")" alt="Profile Image" /></span>
                                <span>
                                    <span>John Smith</span>
                                    <span class="time">3 mins ago</span>
                                </span>
                                <span class="message">
                                    Film festivals used to be do-or-die moments for movie makers. They were where...
                                </span>
                            </a>
                        </li>
                        <li>
                            <a>
                                <span class="image"><img src="@Url.Content("~/Content/Images/userAvathar.jpg")" alt="Profile Image" /></span>
                                <span>
                                    <span>John Smith</span>
                                    <span class="time">3 mins ago</span>
                                </span>
                                <span class="message">
                                    Film festivals used to be do-or-die moments for movie makers. They were where...
                                </span>
                            </a>
                        </li>
                        <li>
                            <a>
                                <span class="image"><img src="@Url.Content("~/Content/Images/userAvathar.jpg")" alt="Profile Image" /></span>
                                <span>
                                    <span>John Smith</span>
                                    <span class="time">3 mins ago</span>
                                </span>
                                <span class="message">
                                    Film festivals used to be do-or-die moments for movie makers. They were where...
                                </span>
                            </a>
                        </li>
                        <li>
                            <div class="text-center">
                                <a>
                                    <strong>See All Alerts</strong>
                                    <i class="fa fa-angle-right"></i>
                                </a>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
</div>
<!-- /top navigation -->

WebAdmin/WebAdmin/Views/Shared/_Mail.cshtml
@Scripts.Render("~/Scripts/ViewScripts/Mail.js")
<br />
<div class="row">
    <div class="col-md-10">
        @using (Html.BeginForm())
            {
        <div class="row">
            <div class="col-md-4">
                <label>Select Message</label>
            </div>
            <div class="col-md-12">
                @{
                    var userRole = Session["UserRole"] != null ? Session["UserRole"] : "";
                    if (userRole.ToString() != "Marketing")
                    {
                        @(Html.ComboBox("message", "Mail").Events(e => e.Select("onSelect")))
                    }
                }
            </div>
            <div class="col-md-4">
                <label>MailSubject</label>
            </div>
            <div class="col-md-12">
               @Html.TextBox("txtMailSubject",null,new { style = "width:100%", @readonly = true })
            </div>
            <div class="col-md-12">
                @(Html.Kendo().Editor()
        .Name("msg_content")
        .Tools(tools => tools.Clear()
        .Formatting()
        .Bold().Italic().Underline()
        .JustifyLeft().JustifyCenter().JustifyRight()
        .InsertUnorderedList().InsertOrderedList().Indent()
        .TableEditing())
        .Value("")
        .Encode(false)
        .HtmlAttributes(new { style = "height:440px,width:800px", aria_label = "editor" }))
            </div>
        </div>
                <span id="err_span" style="color:#d51923"></span>
                    <div class="col-md-4 pull-right">
                        <button id="btnSubmit" type="button" class="saveButton"  tabindex="15"  onclick="sendMessage()" >Send</button>
                    </div>
                    <div class="align row">&nbsp;</div>
        }
    </div>
</div>

WebAdmin/WebAdmin/Views/Shared/_Menu.cshtml
<div class="row">
    <div class="col-md-3 left_col">
        <div class="left_col scroll-view">

            <div class="clearfix"></div>

            <!-- menu profile quick info -->
            <div class="profile clearfix">
                <div class="profile_pic">
                    <img src="/Content/Images/userAvathar.jpg" alt="..." class="img-circle profile_img">
                </div>
                <div class="profile_info">
                    <span>Welcome,</span>
                    <h2>John Doe</h2>
                </div>
            </div>
            <!-- /menu profile quick info -->

            <br>

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                <div class="menu_section">
                    <!-- <h3>General</h3> -->
                    <ul class="nav side-menu">
                        <li id="userdata" class="active">
                            <a  class=""><i class="fa fa-user"></i> User Accounts </a>                          
                        </li>
                        <!--  id="hardwaredata" -->
                       <li id="hardwaredata" class=""> 
                           <a class=""><i class="fa fa-database"></i> Hardware Data </a>
                            </li>

                            <li id="sversions" class="">
                                <a class=""><i class="fa fa-support"></i> Supported Versions </a>
                            </li>
                            <li id="imgresolution" class="">
                                <a class=""><i class="fa fa-image"></i> Image Resolutions </a>
                            </li>
                            <li id="gtin">
                                <a><i class="fa fa-list"></i> GTIN Number </a>
                            </li>
                            <li id="auditlog">
                                <a><i class="fa fa-file"></i>Audit Log Report </a>
                            </li>
                           
                            <li id="country" class="">
                                <a><i class="fa fa-globe"></i>Approved Countries </a>
                            </li>
                        <li id="inactive">
                            <a><i class="fa fa-users"></i>Inactive Users </a>
                        </li>
                        <li id="browser">
                            <a><i class="fa fa-chrome"></i>Browser Details </a>
                        </li>
                        <li id="software">
                            <a><i class="fa fa-list"></i>Software Details </a>
                        </li>
                        @*<li id="Messages">
                            <a><i class="fa fa-envelope"></i>Messages </a>
                        </li>*@

                        <li id="PopupMessages">
                            <a><i class="fa fa-envelope"></i>Popup Messages </a>
                            </li>
                        <li id="EventMessages">
                            <a><i class="fa fa-envelope"></i>Event Messages </a>

                        </li>
                        </ul>
                    </div>
                </div>
                <!-- /sidebar menu -->
            </div>
        </div>
    </div>

    <script>

        $("#userdata").click(function () {
            customGrid.currentPage = customGrid.pageEnums.UserAccounts;
            $.ajax({
                url: '@Url.Action("Index", "User")',
                type: 'POST',
                dataType: "html",
                success: function (data) {
                    $('#content-area').html(data);
                }
            });
        });

        $("#hardwaredata").click(function () {
            customGrid.currentPage = customGrid.pageEnums.HWDate;
            $.ajax({
                url: '@Url.Action("Index", "Hw")',
                type: 'POST',
                dataType: "html",
                success: function (data) {
                    $('#content-area').html(data);
                }
            });
        });
        $("#inactive").click(function () {
            $.ajax({
                url: '@Url.Action("InActive", "User")',
                type: 'POST',
                dataType: "html",
                success: function (data) {
                    $('#content-area').html(data);
                }
            });
        });
        @*$("#reset").click(function () {
            $.ajax({
                url: '@Url.Action("ResetPassword", "Home")',
                type: 'POST',
                dataType: "html",
                success: function (data) {
                    $('#content-area').html(data);
                }
            });
        });*@

        $("#reset").click(function () {
            $.ajax({
                url: '@Url.Action("Index", "Password")',
                type: 'POST',
                dataType: "html",
                success: function (data) {
                    $('#content-area').html(data);
                }
            });
        });
        $("#browser").click(function () {
            $.ajax({
                url: '@Url.Action("Index", "Browser")',
                type: 'POST',
                dataType: "html",
                success: function (data) {
                    $('#content-area').html(data);
                }
            });
        });
        $("#auditlog").click(function () {
            $.ajax({
                url: '@Url.Action("Index", "AuditLog")',
                type: 'POST',
                dataType: "html",
                success: function (data) {
                    $('#content-area').html(data);
                }
            });
        });

        $("#imgresolution").click(function () {
            $.ajax({
                url: '@Url.Action("Index", "Image")',
                type: 'POST',
                dataType: "html",
                success: function (data) {
                    $('#content-area').html(data);
                }
            });
        });

        $("#gtin").click(function () {
            $.ajax({
                url: '@Url.Action("Index", "Gtin")',
                type: 'POST',
                dataType: "html",
                success: function (data) {
                    $('#content-area').html(data);
                }
            });
        });

        $("#sversions").click(function () {
            $.ajax({
                url: '@Url.Action("Index", "ConfigurationSetting")',
                type: 'POST',
                dataType: "html",
                success: function (data) {
                    $('#content-area').html(data);
                }
            });
        });

        $("#country").click(function () {
            $.ajax({
                url: '@Url.Action("Index", "Country")',
                type: 'POST',
                dataType: "html",
                success: function (data) {
                    $('#content-area').html(data);
                }
            });
        });

        $("#software").click(function () {
            $.ajax({
                url: '@Url.Action("Index", "Software")',
                type: 'POST',
                dataType: "html",
                success: function (data) {
                    $('#content-area').html(data);
                }
            });
        });
        $("#Messages").click(function () {
            $.ajax({
                url: '@Url.Action("Index", "Message")',
                type: 'POST',
                dataType: "html",
                success: function (data) {
                    $('#content-area').html(data);
                }
            });
        });

        
        $("#PopupMessages").click(function () {
            $.ajax({
                url: '@Url.Action("Index", "PopupMessage")',
                type: 'POST',
                dataType: "html",
                success: function (data) {
                    $('#content-area').html(data);
                }
            });
        });
        $("#EventMessages").click(function () {
            $.ajax({
                url: '@Url.Action("Index", "EventMessage")',
                type: 'POST',
                dataType: "html",
                success: function (data) {
                    $('#content-area').html(data);
                }
            });
        });
    </script>

WebAdmin/WebAdmin/Views/Shared/_MenuHeader.cshtml
<head>
    <script src="@Url.Content("~/Scripts/layout.js")" type="text/javascript"></script>
</head>
<div class="row tile_count">
    <div class="col-md-3 col-sm-3 col-xs-6 tile_stats_count">
        <span class="count_top"><i class="fa fa-user"></i> Total Users</span>
        <div class="count" id="activeuser" style="padding: 0px 0px 0px 40px"></div>

    </div>
    <div class="col-md-3 col-sm-3 col-xs-6 tile_stats_count">
        <span class="count_top"><i class="fa fa-globe"></i> Countries</span>
        <div class="count" id="inactiveuser" style="padding: 0px 0px 0px 40px"></div>

    </div>
    
        <div class="col-md-3 col-sm-3 col-xs-6 tile_stats_count">
            <span class="count_top"><i class="fa fa-clock-o"></i>Struct</span>
            <div class="count" id="structcount" style="padding: 0px 0px 0px 30px"></div>
        </div>

    <div class="col-md-3 col-sm-3 col-xs-6 tile_stats_count">
        <span class="count_top"><i class="fa fa-globe"></i>   Rings</span>
        <div class="count" id="ringcount" style="padding: 0px 0px 0px 30px"></div>

    </div>

</div>

WebAdmin/WebAdmin/Views/Shared/_Message.cshtml
<div id="msgContent" class="text-center"><h4></h4></div>