WebAdmin/WebAdmin/Models/Setting.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebAdmin
{
    public class Setting
    {
        public int Id { get; set; }

        public string Key { get; set; }

        public string Value { get; set; }
    }
}

WebAdmin/WebAdmin/Models/ViewModels/GtinViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebAdmin
{
    public class GtinViewModel
    {

        [Required(ErrorMessage = "GTIN is required")]      
        public string gtin { get; set; }


      
    }
}

WebAdmin/WebAdmin/Controllers/SettingsController.cs
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Ninject;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebAdmin;
using WebAdmin.Models;

namespace WebAdmin
{
    public class SettingsController : WebAdminController
    {
        private readonly IDataRepository<Setting> resolutionRespository;
        private IEnumerable<Setting> settingValue;
        private readonly IDataRepository<ConfigurationSetting> configurationSettingRepository;
        private readonly IDataRepository<BrowserDetails> browserRepository;
        private ImageResolutionViewModel imageViewModel;
        private GtinViewModel gtinViewModel;
        public SettingsController(IDataRepository<Setting> dataRepository, IDataRepository<ConfigurationSetting> configurationSettingRepository, IDataRepository<BrowserDetails> browserRepository)
        {
            this.resolutionRespository = dataRepository;
            this.configurationSettingRepository = configurationSettingRepository; ;
            this.browserRepository = browserRepository;
        }

        // GET: Settings
        #region Image View
       /// <summary>
            /// To set the model for Gtin and Image
            /// </summary>
            /// <param name="key"></param>
            /// <returns></returns>
        private string SetModel(string key)
        {
            return settingValue?.FirstOrDefault(x => x.Key.Equals(key))?.Value ?? string.Empty;
        }
        /// <summary>
        /// To load Image details
        /// </summary>
        /// <returns></returns>
        public ActionResult Image()
        {

            imageViewModel = new ImageResolutionViewModel();
            try
            {
                if (Session["ImageModel"] == null)
                {
                    settingValue = AsyncUtilHelper.AsyncUtil.RunSync(() => resolutionRespository.GetDatas());

                    imageViewModel.minwidth = int.Parse(this.SetModel("minwidth"));
                    imageViewModel.maxwidth = int.Parse(this.SetModel("maxwidth"));
                    imageViewModel.minheight = int.Parse(this.SetModel("minheight"));
                    imageViewModel.maxheight = int.Parse(this.SetModel("maxheight"));
                    Session["ImageModel"] = imageViewModel;
                }
                else
                {
                    imageViewModel = Session["ImageModel"] as ImageResolutionViewModel;
                }

            }
            catch (Exception exception)
            {
                MvcApplication.Logger.Error(exception.Message, exception);
            }
            return View("Image", imageViewModel);
        }
        /// <summary>
        /// To Update image details
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult> UpdateImage(ImageResolutionViewModel model)
        {
            int update = 0;
            string message = "";
            string textParam = "";
            bool isSuccess = false;

            try
            {
                if (ModelState.IsValid)
                {
                    IDictionary<string, int> dict = new Dictionary<string, int>();
                    dict.Add(new KeyValuePair<string, int>("minwidth", model.minwidth));
                    dict.Add(new KeyValuePair<string, int>("maxwidth", model.maxwidth));
                    dict.Add(new KeyValuePair<string, int>("minheight", model.minheight));
                    dict.Add(new KeyValuePair<string, int>("maxheight", model.maxheight));

                    foreach (KeyValuePair<string, int> entry in dict)
                    {
                        var settingmodel = new Setting
                        {
                            Key = entry.Key,
                            Value = entry.Value.ToString()
                        };
                        update = await resolutionRespository.UpdateById(settingmodel, textParam);
                        if (update != 1) { break; }
                    }
                    Func<string> addSession = () =>
                    {
                        Session["ImageModel"] = model;
                        isSuccess = update == 1;
                        return "Added Successfully";
                    };
                    message = update == 1 ? addSession() : "Failed";
                    return Json(new { message = message, status = isSuccess, keepModelValues = true });
                }
                else
                {
                    isSuccess = false;
                    IList<object> modelStateErrors = DataHelper.ModelStateErrors(ModelState);
                    return Json(new { message = message, status = isSuccess, validationErrors = modelStateErrors });
                }
            }
            catch (Exception ex)
            {
                MvcApplication.Logger.Error(ex.Message, ex);
                throw ex;
            }
        }
#endregion

        #region GTIN View
        /// <summary>
        /// To get the Gtin value
        /// </summary>
        /// <returns></returns>
        public ActionResult Gtin()
        {
            gtinViewModel = new GtinViewModel();
            try
            {
                if (Session["gtin"] == null)
                {
                    this.settingValue = AsyncUtilHelper.AsyncUtil.RunSync(() => resolutionRespository.GetDatas());
                    gtinViewModel.gtin = this.SetModel("gtin");
                    Session["gtin"] = gtinViewModel.gtin;
                }
                else
                {
                    gtinViewModel.gtin = Session["gtin"].ToString();
                }
            }
            catch (Exception exception)
            {
                MvcApplication.Logger.Error(exception.Message, exception);
            }
            return View("Gtin", gtinViewModel);
        }
        /// <summary>
        /// To update the Gtin value
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>

        [HttpPost]
        public async Task<ActionResult> UpdateGtin(GtinViewModel model)
        {
            int update = 0;
            string msg = "";
            string textParam = "";
            bool isSuccess = false;
            try
            {
                if (ModelState.IsValid)
                {
                    string gtinno = model.gtin;
                    var modelsetting = new Setting
                    {
                        Key = "gtin",
                        Value = gtinno
                    };
                    update = await resolutionRespository.UpdateById(modelsetting, textParam);
                    if (update == 1)
                    {
                        isSuccess = true;
                        msg = "Updated Successfully";
                        TempData["gtin"] = gtinno;
                        Session["gtin"] = gtinno;

                    }
                    else
                    {
                        isSuccess = false;
                        msg = "Updation Failed";
                    }
                    return Json(new { message = msg, status = isSuccess, keepModelValues = true });
                }
                else
                {
                    isSuccess = false;
                    IList<object> modelStateErrors = DataHelper.ModelStateErrors(ModelState);
                    return Json(new { message = msg, status = isSuccess, validationErrors = modelStateErrors });
                }
            }
            catch (Exception ex)
            {
                MvcApplication.Logger.Error(ex.Message, ex);
                throw ex;
            }
        }
        #endregion


        #region SupportedVersion
        /// <summary>
        /// To load Supported version view
        /// </summary>
        /// <returns></returns>
        public async Task<ActionResult> ConfigurationSettingIndex()
        {
            var configViewModel = new ConfigurationSettingViewModel();
            var selectList = new List<SelectListItem>();
            try
            {
                
                MvcApplication.Logger.Info("Supported Version Details");
                IEnumerable<BrowserDetails> selectData = await browserRepository.GetDatas();
                
                foreach (BrowserDetails data in selectData)
                {
                    selectList.Add(
                         new SelectListItem
                         {
                             Value = data.Id.ToString(),
                             Text = data.BrowserName // + " From " + data.BrowserMinorVersion + " Version"
                         });

                }
                var BrowserTip = new SelectListItem()
                {
                    Value = null,
                    Text = "--- select Browser ---"
                };
                selectList.Insert(0, BrowserTip);

                configViewModel.BrowserList = new SelectList(selectList, "Value", "Text");

                
            }
            catch (Exception ex)
            {
                MvcApplication.Logger.Error(ex.Message, ex);
                //throw ex;
            }
            return View(configViewModel);
        }

        /// <summary>
        /// To add new configuration details
        /// </summary>
        /// <param name="st"></param>
        /// <returns></returns>
        [HttpPost]        
        public async Task<ActionResult> ConfigurationSettingAdd(ConfigurationSettingViewModel st)
        {
            string message = string.Empty;
           
                    MvcApplication.Logger.Debug("Added Supported Version Details");
            try
            {
                var getAll = AsyncUtilHelper.AsyncUtil.RunSync(() => browserRepository.GetDatas());

WebAdmin/WebAdmin/Views/Settings/Gtin.cshtml
@model GtinViewModel
@{
    ViewBag.Title = "Index";
    Layout = Request.IsAjaxRequest() ? null : "~/Views/_Layout.cshtml";
}
@Scripts.Render("~/Scripts/gtin")
<div class="form_container">
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_content">
                    <h4>GTIN Number</h4>
                    @using (Html.BeginForm())
                    {
                        <div class="row content_border">
                            <div class="panel_color">
                            </div>
                            <div class="col-md-8 col-sm-10 col-xs-12">
                                <div class="align row">
                                    <div class="left_align col-md-3 col-sm-4 col-xs-6">
                                        <label>GTIN Number</label><label style="color:red">&nbsp;*</label>
                                    </div>
                                    <div class="col-md-5 col-sm-10 col-xs-12">
                                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                        @Html.TextBoxFor(m => m.gtin, new { @class = "form-control text-right",tabindex = 1 })
                                        @Html.ValidationMessageFor(m => m.gtin, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                <div class="save row ">
                                    <div class="col-md-8 col-sm-10 col-xs-12">
                                        <button type="button" class="saveButton" tabindex="2" onclick="saveGTIN('@Url.Action("UpdateGtin", "Settings")')">Save</button>
                                        <button type="button" class="cancelButton" tabindex="2" onclick="clearGtin('@Url.Action("Gtin","Settings")')">Cancel</button>
                                        <div class="align row">&nbsp;</div>
                                        <div><label style="color:red;font-weight:normal"> * Indicates Required Field</label></div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

WebAdmin/WebAdmin/Views/Settings/Image.cshtml
@model ImageResolutionViewModel
@using Kendo.Mvc.UI;
@{
    ViewBag.Title = "Index";
    Layout = Request.IsAjaxRequest() ? null : "~/Views/_Layout.cshtml";
}

@Scripts.Render("~/Scripts/image")
<div class="form_container">
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_content">
                    <h4>Edit X-ray image resolution limits</h4>
                    @using (Html.BeginForm())
                    {
                        <div class="row content_border">
                            <div class="panel_color">
                            </div>
                            <div class="col-md-6 col-sm-10 col-xs-12">
                                <div class="align row">
                                    <div class="left_align col-md-3 col-sm-4 col-xs-6">
                                        <label>Minimum Width</label><label style="color:red">&nbsp;*</label>
                                    </div>
                                    <div class="right col-md-5 col-sm-5 col-xs-6">
                                        @Html.TextBoxFor(m => m.minwidth, new { @class = "form-control", tabindex = 1, onclick = "utility.clearValidationMessage(false,this)", @type = "number" })
                                        @Html.ValidationMessageFor(m => m.minwidth, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="align row">
                                    <div class="left_align col-md-3 col-sm-4 col-xs-6">
                                        <label>Maximum Width</label><label style="color:red">&nbsp;*</label>
                                    </div>
                                    <div class="col-md-5 col-sm-5 col-xs-6">
                                        @Html.TextBoxFor(m => m.maxwidth, new { @class = "form-control", tabindex = 2, onclick = "utility.clearValidationMessage(false,this)", @type = "number" })
                                        @Html.ValidationMessageFor(m => m.maxwidth, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="align row">
                                    <div class="left_align col-md-3 col-sm-4 col-xs-6">
                                        <label>Minimum Height</label><label style="color:red">&nbsp;*</label>
                                    </div>
                                    <div class="col-md-5 col-sm-5 col-xs-6">
                                        @Html.TextBoxFor(m => m.minheight, new { @class = "form-control", tabindex = 3, onclick = "utility.clearValidationMessage(false,this)" , @type = "number" })
                                        @Html.ValidationMessageFor(m => m.minheight, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="align row">
                                    <div class="left_align col-md-3 col-sm-4 col-xs-6">
                                        <label>Maximum Height</label><label style="color:red">&nbsp;*</label>
                                    </div>
                                    <div class="col-md-5 col-sm-5 col-xs-6">
                                        @Html.TextBoxFor(m => m.maxheight, new { @class = "form-control text-danger", tabindex = 4, onclick = "utility.clearValidationMessage(false,this)" ,@type = "number" })
                                        @Html.ValidationMessageFor(m => m.maxheight, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="save row">
                                    <div class="col-md-3 col-sm-4 col-xs-6">
                                    </div>
                                    <div class="col-md-5 col-sm-5 col-xs-6">
                                        <button type="button" class="saveButton" tabindex="5" onclick="saveImage('@Url.Action("UpdateImage","Settings")')">Save</button>
                                        <button type="button" class="cancelButton" tabindex="2" onclick="clearImageDimensions('@Url.Action("Image","Settings")')">Cancel</button>
                                    </div>

                                </div>
                                <div><label style="color:red;font-weight:normal"> * Indicates Required Field</label></div>

                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>

    </div>
</div>